- UMM/UMM.xcdatamodeld/UMM.xcdatamodel/contents
- #21 
- Travel Entity의 startDate의 데이터 타입을 String?으로 변경
여행 안에서의 정산은 일자까지만 필요할꺼 같아서 기존에 Date?타입을 String?타입으로 변경하였습니다.
> 🧹[#21] startDate의 데이터 타입을 String?으로 변경합니다.

- UMM/UMMApp.swift
- #24
- UMMApp.swift 파일에서 환경 객체 생성하고 뷰에 주입하는 라인을 삭제했습니다.
- 뷰모델 안에서는 PersistenceController의 싱글톤으로 viewContext에 접근해주세요!
> :broom:[#24] UMMApp에서 환경객체 삭제

- UMM/ViewModel/RecordViewModel.swift
- #30
- RecordViewModel의 voiceSentenceChoicer 변수 앞에 private을 붙였습니다.
-
- @GYURI-PARK 의 코드 리뷰를 반영해서, 뷰 모델 안의 메서드에서만 사용되는 변수에 private을 붙였습니다.
- 테스트용 버튼의 동작에 관여하는 메서드 alterVoiceSentence()에서 사용되는 변수입니다.
> :broom:[#30] RecordViewModel의 voiceSentenceChoicer 변수 앞에 private을 붙였습니다.

- UMM.xcodeproj/project.pbxproj
- UMM/UMMApp.swift
- UMM/View/RecordView.swift
- UMM/ViewModel/RecordViewModel.swift
- #20 
- 임의의 녹음 버튼을 누르고 있는 동안만 녹음이 가능하도록 구현
https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/93391058/572c404e-f9c2-4f8f-9270-de83258db94f
- 변환된 문장은 `voiceSentenceTemp`에 저장함
- 제스쳐 두개를 사용하다보니 두번째 눌렀을 때부터 기능 작동함 (방법 찾으면 수정 예정 아직은 못찾음)
- 빠르게 말하면 글자 하나하나씩이 아닌 단어 단위로 한번에 띄워지는데 이것도 방법 찾으면 추가하겠음
LongPressGesture의 minimumDuration의 값을 .infinity로 설정하면 사용자가 원하는 만큼 제스처를 유지할 수 있었지만 제스처가 끝난 상태(손을 뗀 후)를 인식하지 못했다. 
```swift
.gesture(
LongPressGesture(minimumDuration: .infinity)
.updating($press) { currentState, gestureState, transaction in
gestureState = currentState
}
.onEnded { value in
show.toggle()
print("끝")
}
)
```
</br>
위와 같이 코드를 짰었는데 onEnded 매서드가 실행되지 않았다. </br>
그래서 .sequenced를 사용해 Long Press Gesture 전에 하나의 제스처를 더 추가하는 방식으로 문제를 해결하고자 했다. </br>
```swift
var continuousPress: some …
```
> ⚡️[#20] STT 기능을 구현합니다.

- UMM.xcodeproj/project.pbxproj
- UMM/DesignSystem/ButtonTheme.swift
- UMM/View/MainView.swift
- UMM/View/Travel/AddMemberView.swift
- UMM/View/Travel/AddTravelView.swift
- UMM/View/Travel/CompleteAddTravelView.swift
- UMM/ViewModel/AddTravelViewModel.swift
- #47 
- #58 
- 달력의 테두리 크기 수정
- 종료일 표시
- 시작일과 종료일을 눌렀을 때 DatePicker 추가
- AddMemberView 뷰 찍먹
- 정산 멤버 추가
- 추가 수정 사항들은 이슈에 올려놓을 예정입니다.
- 현재 정산 멤버들 추가는 최대 4명까지로 List를 만들어놓았는데 이후 추가 예정입니다.
- 달력에 year값 반영, 여행 기간 전체 그라데이션 등등...
- 빨리 CoreDate에 값 추가 하는거 하고 싶어서 대충 그렸어요....계속 수정할게요 ~~~~~
- 시작일과 종료일을 입력하면 자꾸 뷰가 밀린다ㅜㅜㅜㅜㅜ
> ⚡️[#47][#58] AddTravelView와 AddMemberView 데이터 선택 기능을 구현합니다.

- UMM.xcodeproj/project.pbxproj
- UMM/DesignSystem/Fonts/FontsManager.swift
- UMM/Extension/Font+Extension.swift
- UMM/View/MainView.swift
- #57 
- 피그마에 있는 이름을 보고 바로 적용할 수 있도록 Custom 폰트를 적용합니다.
- 사용법
```swift
.font(.display1)
```
기존에 Font Manager에서 변수 형태로 저장한 폰트들을 Font 타입에서만 활용할 수 있도록 `Extension`으로 따로 뺴주었습니다 !
> 🧩[#57] Typography 적용합니다.

- UMM/View/Record/RecordView.swift
- UMM/ViewModel/RecordViewModel.swift
- #70
- 녹음 버튼을 여러 번 눌러도 처음처럼 동작하도록 stopSTT() 메서드의 내용에 몇 가지를 추가했습니다. 
- 녹음 버튼을 누를 때와 뗄 때의 동작을 정리했습니다.
-
- 이제 앱을 끄지 않아도 음성 녹음을 여러 번 할 수 있습니다.
- startRecording()은 비동기로 넘겼습니다.
- startSTT()는 메인 스레드에 놔뒀습니다. 확실하지는 않은데, async로 바꿔서 다른 스레드로 보내보니 인식능력이 떨어져 보였습니다.
> :bug:[#70] 녹음 한 번만 되는 에러 해결

- UMM.xcodeproj/project.pbxproj
- UMM/Extension/NSObject+Extension.swift
- UMM/UMMApp.swift
- UMM/View/Expense/AllExpenseView.swift
- UMM/View/Expense/CustomDatePicker.swift
- UMM/View/Expense/ExpenseView.swift
- UMM/View/Expense/TodayExpenseView.swift
- UMM/View/MainView.swift
- UMM/ViewModel/ExpenseViewModel.swift
- #75 
- TodayExpenseView의 gui 구현 완료
- custom datePicker 적용
- custom tabBarItem 적용
- 미적용: enum을 실제 값으로 보이게
- 미적용: 올리버의 Travel Modal
- 미적용: 아이콘 이미지
DatePicker의 버튼을 커스텀 하되, 기본 DatePicker의 pop over가 나오게 하고자 했습니다.
다른 함수로 DatePicker를 호출하려고 했으나, 기본적으로 제공되지 않아 StackOverFlow를 참고했습니다.
```
// 호출하는 함수
func triggerDatePickerPopover(pickerId: String) {
if
let scene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
let window = scene.windows.first,
let picker = window.accessibilityDescendant(identifiedAs: pickerId) as? NSObject,
let button = picker.buttonAccessibilityDescendant() as? NSObject
{
button.accessibilityActivate()
}
}
```
```
// DatePicker 호출 부분
ZStack {
Button {
expenseViewModel.triggerDatePickerPopover(pickerId: pickerId)
} label: {
Text("\(expenseViewModel.selectedDate, …
```
> 🎨 [#75] TodayExpenseView의 gui 구현 완료

- UMM/View/Travel/AddMemberView.swift
- UMM/View/Travel/AddTravelView.swift
- UMM/View/Travel/PreviousTravelView.swift
- UMM/View/Travel/TravelListView.swift
- UMM/View/Travel/UpcomingTravelView.swift
- UMM/ViewModel/TravelListViewModel.swift
- #91 
- #118 
- #119 
- 디데이 계산 함수를 추가
- 각각의 page indicator 수정
- 탭 바 아이템에 가로선 추가
- 임시 기록뷰의 UI 구현
- AddMemberView에서 뒤로 가기 버튼을 눌렀을 때도 여행이 생성되는 오류 수정
- 아직 tabView들 사이의 padding을 주는 방법을 찾지 못했어요..🥹
- 시간 기준이 한국이 아니라서 디데이 계산에 차이가 생깁니다.
- tabView에 기본으로 생기는 padding이 존재해서 page indicator의 위치를 VStack으로 해결할 수 없어서 offset으로 지정했습니다...
- page indicator
```swift
HStack(spacing: 6) {
ForEach(0..<travelCount, id: \.self) { index in
Capsule()
.fill(currentPage == index ? Color.black : Color.gray200)
.frame(width: 5, height: 5)
}
}
.offset(y: 60)
.onAppear {
let screenWidth = getWidth()
self.currentPage = Int(round(offset / screenWidth))
}
var offset: CGFloat {
let screenWidth = getWidth()
return CGFloat(currentPage) * screenWidth
}
func getWidth() -> CGFloat {
return UIScreen.main.bounds.width
}
```
> 화면 크기를 …
> ⚡️[#91][#118][#119] 임시기록 뷰를 만들고 TravelListView의 디테일 수정 및 AddMemberView의 오류를 수정합니다.

- UMM.xcodeproj/project.pbxproj
- UMM/View/Travel/CompleteAddTravelView.swift
- UMM/View/Travel/PreviousTravelView.swift
- UMM/View/Travel/TravelDetailView.swift
- UMM/View/Travel/TravelListView.swift
- UMM/View/Travel/UpcomingTravelView.swift
- UMM/ViewModel/PreviousTravelViewModel.swift
- UMM/ViewModel/TravelDetailViewModel.swift
- UMM/ViewModel/UpcomingTravelViewModel.swift
- #122 
- TravelDetailView에 데이터를 추가합니다. (국가 관련 제외)
- HIFI보며 정렬 작업
- 추후 국가 인덱스를 추가할 경우 1. 배경에 들어갈 사진 2. 국기 이미지 3. 국가 이름 데이터를 추가할 예정
- Detail 뷰의 변경 사항이 TravelListView에 반영되어야 할 상황에 대비해 데이터 전달과정에서 이니셜라이저는 사용하지 않았습니다.
> ⚡️[#122] TravelDetailView에 데이터를 추가합니다.

- UMM/View/Modal/CountryChoiceModal.swift
- UMM/View/Record/ManualRecordView.swift
- UMM/View/Record/RecordView.swift
- UMM/ViewModel/ManualRecordViewModel.swift
- UMM/ViewModel/RecordViewModel.swift
- #142
- 포매터를 이용해서 한화로 계산된 작은 괄호 안의 금액에 쉼표를 넣었습니다.
- 지출 장소 수정한 다음부터는 상세주소 Text를 TextField로 대체해서 수정 가능하게 했습니다.
- 결제 인원 버튼을 여러 행에 걸쳐 보여주고 한 행에 세 명씩 배치했습니다.(Hi-fi 수정사항 반영)
- 결제 인원의 플러스 버튼을 없앴습니다.(Hi-fi 수정사항 반영)
- 5초 + 3초 후 자동 저장 타이머와 화면 표현을 구현했습니다. (조작이 있으면 타이머가 invalidate됩니다.)
- 커스텀으로 구현된 네비게이션 바를 기본 코드로 바꿨습니다.
- 뒤로가기 누르면 경고창을 띄웁니다.
- 음성으로 소숫점 뒤 자리 없는 금액을 입력했을 때 ManualRecordView에서 불필요한 ".0"이 붙는 문제를 해결했습니다.
- ManualRecordView에서 아직 구현하지 않은 것은 아래와 같습니다:
- 지출 일시 수정 기능
- 녹음된 소리 저장과 재생
- 한국, 일본, 베트남 화폐는 소숫점 표시 없애기
- 키보드 관련 문제들(키보드 따라 칸도 올리기, 바깥 터치했을 때 키보드 내리기) 해결하기
- 네비게이션 바는 통일성을 위해 @GYURI-PARK의 뷰와 거의 같은 형식으로 만들었습니다. 스크롤해도 배경이 하얀색으로 유지되도록 아래의 코드를 추가했습니다:
```
.toolbarBackground(.white, for: .navigationBar)
```
- 경고창 등 몇 가지 기능을 넣기 위해 뷰모델에 뷰의 상태를 반영하는 State Bool 변수를 여러 개 추가했습니다.
- 불필요한 ".0"이 붙는 …
> 🎨[#142] ManualRecordView를 어느 정도 완성합니다.

- UMM/View/Expense/AllExpenseView.swift
- UMM/View/Expense/TodayExpenseView.swift
- #163 
- TodayExpenseView와 AllExpenseView에 표시할 지출 기록이 없는 경우, 표시할 noDataView를 추가
- filteredTodayExpenses, filteredAllExpenses를 지출 기록의 판단 기준으로 삼았습니다.
> 🎨 [#163] TodayExpenseVIew와 AllExpenseView에 지출 기록이 없는 경우, 표시할 View 추가

- UMM/View/Expense/AllExpenseView.swift
- UMM/View/Expense/TodayExpenseDetailView.swift
- UMM/View/Expense/TodayExpenseView.swift
- UMM/ViewModel/ExpenseViewModel.swift
- #173 
- Expense 관련 뷰에 CountryInfo를 적용
- Expense 관련 뷰에 국기 이미지의 GUI를 HIFI에 맞게 수정
- TodayExpenseView에 chevron을 디자이너 모르게 수정 (지금은 아는 상태)
~~TodayExpenseView의 chevron은 수정할 예정입니다.~~ 완료
> ⚡ 🎨 [#173] Expense 관련 뷰에 CountryInfo를 적용합니다. 국기 이미지를 HIFI에 맞춰 수정합니다.

- UMM/View/Record/ManualRecordView.swift
- UMM/View/Record/RecordView.swift
- UMM/ViewModel/ManualRecordViewModel.swift
- UMM/ViewModel/RecordViewModel.swift
- #196
- ManualRecordView 저장 버튼이 갑자기 너무 아래로 옮겨져서 위치 조정
- ManualRecordViewModel의 save() 메서드 안에 Currency 이뉴머레이션을 아직 사용하는 코드 있는데 그것 수정
- ManualRecordView에서 지출 저장하고서 불필요한 오디오 파일 삭제하기
-
- 녹음 버튼 누를 때 '저장되었습니다' 안내를 없애고 싶었는데 STT가 멈춰버리는 문제가 있어서 없애지 못했습니다.
> 🎨[#196] ManualRecordView 소소한 수정을 합니다.

- UMM/View/Expense/AllExpenseDetailView.swift
- UMM/View/Expense/TodayExpenseDetailView.swift
- UMM/View/Record/ManualRecordInExpenseView.swift
- UMM/ViewModel/ManualRecordInExpenseViewModel.swift
- #218 
- TodayExpenseDetailView: ManualRecordInExpenseView 연결
- TodayExpenseDetailView: 데이터 조회, 수정, 저장 구현
- AllExpenseDetailView: ManualRecordInExpenseView 연결
- AllExpenseDetailView: 데이터 조회, 수정, 저장 구현
- DetailView에서 백 버튼에 "뒤로" 텍스트 삭제
"DetailView에서 백 버튼에 "뒤로" 텍스트 삭제"에 대한 영상입니다.
ManualRecordViewModel에 data를 인자로 받는 startPlayingAudio() 함수를 작성했습니다. @oliver-or-not 
CoreData에 저장된 오디오 파일을 재생하는 데에 어려움을 겪었습니다.
@oliver-or-not 가 사용하는 함수는 임시로 생성한 File Manager를 URL로 접근해서 실행하는 방식입니다.
제가 필요한 방식은 Binary data 타입을 저장된 오디오 파일을 즉시 실행하는 방식입니다.
하지만 즉시 실행하는 방식이 어려웠습니다.
현재 구현한 방식은 data를 받아서, 임시 URL을 생성해서 재생하는 방식입니다.
앞으로 개선 방향은 2가지 있습니다.
1. Binary Data를 즉시 실행하도록 개선
2. 생성한 임시 URL을 적절한 시점에 삭제하도록 개선
> ⚡ 🎨 [#218] DetailView와 ManualRecordInExpenseView를 연결하고 기능을 구현했습니다.

- UMM/View/Record/InterimOncomingView.swift
- UMM/View/Record/InterimPastView.swift
- UMM/View/Record/InterimProceedingView.swift
- UMM/View/Record/InterimRecordView.swift
- UMM/View/Travel/AddMemberView.swift
- UMM/View/Travel/AddTravelView.swift
- UMM/View/Travel/CompleteAddTravelView.swift
- UMM/View/Travel/PreviousTravelView.swift
- UMM/View/Travel/TravelDetailView.swift
- UMM/View/Travel/TravelListView.swift
- UMM/View/Travel/UpcomingTravelView.swift
- UMM/ViewModel/CompleteAddTravelViewModel.swift
- UMM/ViewModel/InterimRecordViewModel.swift
- UMM/ViewModel/TravelListViewModel.swift
- #216 
- #222 
-  Travel 관련 뷰들의 수정사항을 반영합니다.
- 여행 참여자 관련 코드를 수정합니다
endDate를 다음과 같이 처리해주었을 때 인식을 못하는 오류가 있어서 임시로 주석처리하고 local235959() 처리를 하지 않았습니다.
```swift
if let endDate = viewModel.endDate {
viewModel.endDate = endDate.local235959().convertBeforeSaving()
} else {
viewModel.endDate = nil
}
```
nowTravelingView에서 nowTravel의 개수가 0개여도 nowTravel이 0이 아닐 때 뷰의 onAppear가 실행되면서  nowTravel?[index].id  해당 코드에서 오류가 발생했었는데 , 해당 코드를 조건문안에 넣어서 해결했습니다. 
```swift
if index > 0 {
self.savedExpenses = viewModel.filterExpensesByTravel(selectedTravelID: nowTravel?[index].id ?? UUID())
}
```
> ⚡️🎨[#216][#222] Travel 관련 뷰들의 수정사항을 반영합니다.

- UMM/Handler/DateGapHandler.swift
- UMM/View/MainView.swift
- #259
- 앱 삭제하고 새로 설치하고 처음 실행할 때 위치 정보를 묻는 창이 보이지 않아 앱이 멈춰보이는 문제를 해결했습니다.
- 기존에는 앱을 inactive 상태로 만들어서 묻는 창을 보아야 했습니다.
-
-
- 위치 정보를 처음 사용하는 함수를 MainView의 onAppear에서 호출해도 해결되지 않아서, onAppear에서도 1초 미뤄서 실행했습니다.
> :bug:[#259] 위치 정보 허용 창 안 떠서 앱이 멈춰보이는 문제 해결

- UMM/Handler/DateGapHandler.swift
- UMM/View/Record/ManualRecordInExpenseView.swift
- UMM/ViewModel/ManualRecordInExpenseViewModel.swift
- UMM/ViewModel/ManualRecordViewModel.swift
- #267 
- ManualRecordInExpenseView에서 participantArray가 정상 작동하도록 수정
```
private init() {
timer = Timer.scheduledTimer(withTimeInterval: 3.0, repeats: true) { _ in
//            print("DateGapHandler | location: \(self.currentLocation?.description ?? "nil")")
//            print("DateGapHandler | timeDifference: \(self.timeDifferenceInterval.description)")
}
}
```
DateGapHandler에서 3초마다 print 하는 부분을 주석 처리하였습니다.
필요한 부분이라면 되살려서 commit 하도록 하겠습니다. 
@oliver-or-not 확인 부탁해요 ~
```
// ManualRecordInExpenseView.swift
if let participantArray = MainViewModel.shared.chosenTravelInManualRecord?.participantArray {
viewModel.participantTupleArray = participantArray.map { participant in
let isSelected = given_expense.participantArray?.contains(participant) ?? false
return (name: participant, isOn: …
```
> :bug:[#267] ManualRecordInExpenseView에서 participantArray가 정상 작동하도록 수정

- UMM.xcodeproj/project.pbxproj
- UMM/View/Travel/AddMemberView.swift
- UMM/View/Travel/CompleteAddTravelView.swift
- UMM/View/Travel/TravelButtonView.swift
- UMM/View/Travel/TravelDetailView.swift
- UMM/ViewModel/AddMemberViewModel.swift
- UMM/ViewModel/InterimRecordViewModel.swift
- UMM/ViewModel/PreviousTravelViewModel.swift
- UMM/ViewModel/TravelListViewModel.swift
- UMM/ViewModel/UpcomingTravelViewModel.swift
- #307 
- #308 
- TravelDetailView에서 아직 지출기록이 없을 경우 문구 추가 (임의로 내가 정한 문구)
- TravelButtonView에서 두 번 클릭 시 선택 해제
- TravelButonView에서 나라가 하나만 선택되도록 수정
- AddMemberView에서 빼먹은 dateGapHandler 적용
- AddMemberViewModel에서 함수를 정의해 **중복 / 빈 문자열 / 나** 제거
- @oliver-or-not 가 찾은 여행 filter시 convertBeforeShowing() 처리
- 임시기록
- 여행 생성
여행 참여자를 추가하는 플로우에서 혹시 빼먹은 케이스가 있는지 확인 부탁드려요..🥹
```swift
if participantArr.count == 1 && self.isSelectedTogether == true {
viewModel.travelName = "\(participantArr[0])님과의 여행"
viewModel.participantArr = participantArr
} else if participantArr.count == 0 && self.isSelectedAlone == true {
viewModel.participantArr = participantArr
viewModel.travelName = "나의 여행"
} else if participantArr.count == 0 {
viewModel.travelName = "나의 여행"
viewModel.participantArr = participantArr
} else { …
```
> 🎨⚡️[#307][#308] (Travel 관련) 버전 1.1.1이후 수정사항들을 반영합니다.

- UMM/View/Travel/TravelDetailView.swift
- UMM/View/Travel/TravelListView.swift
- UMM/View/Travel/UpcomingTravelView.swift
- #311 
- 최초 임시기록 시 UI가 깨지는 오류를 해결
- TravelListView가 onAppear될 때 TravelTabView를 항상 다시 그릴 수 있도록 함
- TabView안에 있는 것들만 위치를 찾지 못하는 이유를 모르겠음
```swift
struct TravelTabView: View {
@State private var currentTab: Int = 0
var body: some View {
ZStack(alignment: .top) {
TabView(selection: self.$currentTab) {
PreviousTravelView()
.gesture(DragGesture().onChanged { _ in
// PreviousTravelView에서 DragGesture가 시작될 때의 동작
})
.tag(0)
UpcomingTravelView()
.gesture(DragGesture().onChanged { _ in
// PreviousTravelView에서 DragGesture가 시작될 때의 동작
})
.tag(1)
}
.padding(.top, 12)
.tabViewStyle(.page(indexDisplayMode: .never))
Divider()
.frame(height: 1)
.padding(.top, 36)
TabBarView(currentTab: self.$currentTab)
}
}
}
```
> 🔨[#311] 최초 임시기록 시 UI가 깨지는 오류를 해결합니다.

- UMM.xcodeproj/project.pbxproj
- UMM/Utils/Constants.swift
- UMM/View/Record/InterimOncomingView.swift
- UMM/View/Record/InterimPastView.swift
- UMM/View/Record/InterimProceedingView.swift
- UMM/View/Travel/PreviousTravelView.swift
- UMM/View/Travel/TravelButtonView.swift
- UMM/View/Travel/TravelItemView.swift
- UMM/View/Travel/UpcomingTravelView.swift
- #335 
- SE화면 비율에서도 UI가 깨지지 않도록 하였습니다.
상수 구조체를 사용한 부분
- InterimRecordView의 여행 개수
- InterimRecordView의 offset 위치
- TravelButtonView의 frame 크기
- TravelItemView의 frame 크기
- 지난여행/다가오는 여행의 offset 위치
앞으로 UIScreen을 쓰지 못한다면.... 수정해야합니다..🥹
> 🎨[#335] TravelListView의 화면을 SE 화면비율을 고려합니다.
