DeveloperAcademy-POSTECH/MacC-Team11-UMM

- UMM.xcodeproj/project.pbxproj
- #2 
- 일관성있는 코드 작성을 위해 SwiftLint를 적용합니다.
> :broom: [#2] SwiftLint적용

- UMM.xcodeproj/project.pbxproj
- UMM/ContentView.swift
- UMM/UMM.xcdatamodeld/UMM.xcdatamodel/contents
- #8
- 피그잼에서 작성한 데이터베이스 모델 설계를 참고하여, Core Data 초기 세팅 완료
- swift와 core data의 옵셔널의 의미가 다름
- 음성파일의 타입 모름...
- derived attribute 포기
- Int 종류의 attribute 초기값을 -1로 설정
> :zap:[#8] 코어데이터 초기 세팅 완료

- UMM.xcodeproj/project.pbxproj
- UMM/ContentView.swift
- UMM/Persistence.swift
- UMM/UMMApp.swift
- #8
- Persistence 파일 추가
- 앱 메인 파일에서 환경객체 생성하고 최상위 뷰에 주입
폴더 정리는 아직 하지 않았습니다.
> :zap:[#8] Persistence 파일 추가, 앱 메인 파일에서 환경객체 추가

- UMM/Persistence.swift
- UMM/UMMApp.swift
- #12 
- SwiftLint 경고 코드 처리
1. ❗️이제 merge하기 전에 브랜치 Pull 해서 확인하고 코드리뷰 하는게 좋을꺼 같아요❗️
2. Core Data 관련해서 아래와 같은 경고들이 뜹니다.
> ⚡️[#12]SwiftLint 규칙에 따라 수정

- UMM/UMM.xcdatamodeld/UMM.xcdatamodel/contents
- #39
- stardDate의 데이터 타입을 변경합니다.
- 전에 데이터 타입을 변경하면 프리뷰에서 오류가 났었는데 페페가 알려준 방식을 다시 써야할 것 같아요 !!
https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/issues/23
> 🧹[#39] startDate의 데이터 타입을 변경합니다.

- UMM.xcodeproj/project.pbxproj
- UMM/View/Travel/AddMemberView.swift
- UMM/View/Travel/AddTravelView.swift
- UMM/View/Travel/TravelListView.swift
- UMM/ViewModel/AddMemberViewModel.swift
- UMM/ViewModel/CompleteAddTravelViewModel.swift
- #64 
- AddMemberView에서 완료 버튼 클릭 시 startDate, endDate, participantArr가 Core Data에 저장됩니다.
- 출력을 저장되었음을 확인하였습니다.
- fetchTravel 함수는 구현되어있지만 사용되지 않았습니다.
Button기능과 NavigationLink 사이에 기능 충돌이 일어나 버튼에서는 뷰 이동만 일어나고, 기존에 버튼 클릭 시 일어나야되는 기능을 onDisappear을 통해 구현하였습니다.
> ⚡️[#64] 시작일, 종료일, 정산자 데이터를 Core Data에 저장합니다.

- UMM.xcodeproj/project.pbxproj
- UMM/View/Other/SettingView.swift
- UMM/View/Travel/AddMemberView.swift
- UMM/View/Travel/CompleteAddTravelView.swift
- UMM/View/Travel/PreviousTravelView.swift
- UMM/View/Travel/TravelListView.swift
- UMM/View/Travel/UpcomingTravelView.swift
- UMM/ViewModel/CompleteAddTravelViewModel.swift
- UMM/ViewModel/PreviousTravelViewModel.swift
- UMM/ViewModel/TravelListViewModel.swift
- UMM/ViewModel/UpcomingTravelViewModel.swift
- #69 
- TravelListView를 구현합니다.
- Date+Extension에 있는 DateFormatter를 사용하려고 했지만 *The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions* 다음과 같은 컴파일러 오류가 발생해 뷰모델에서 따로 정의하였습니다.
- TabView의 Page indicator Custom 필요합니다.
- 사진은 국가에 맞춰서 가져오는거라서 각 여행의 국가 데이터를 가져오는 코드가 필요합니다.
- 사진 에셋을 몇개 더 추가해서 국가에 맞는 사진을 가져와볼 예정입니다.
- DispatchQueue 어떻게 처리할지 고민중.. 추후 수정할 예정입니다.
> ⚡️[#69] TravelListView를 구현합니다.

- UMM/Assets.xcassets/Primary/graphCyan.colorset/Contents.json
- UMM/Assets.xcassets/Primary/graphOrange.colorset/Contents.json
- UMM/Assets.xcassets/Primary/graphPurple.colorset/Contents.json
- UMM/Assets.xcassets/Primary/graphRed.colorset/Contents.json
- UMM/Assets.xcassets/Primary/graphYellow.colorset/Contents.json
- UMM/Extension/Font+Extension.swift
- #93 
- 피그마에 따라 추가된 폰트와 색상을 추가했습니다.
> 🧩[#90] 추가된 폰트와 색상을 추가합니다.

- UMM/Assets.xcassets/Modal/modalCategoryFood.imageset/Contents.json
- UMM/Assets.xcassets/Modal/modalCategoryFun.imageset/Contents.json
- UMM/Assets.xcassets/Modal/modalCategoryPlane.imageset/Contents.json
- UMM/Assets.xcassets/Modal/modalCategoryRoom.imageset/Contents.json
- UMM/Assets.xcassets/Modal/modalCategoryShopping.imageset/Contents.json
- UMM/Assets.xcassets/Modal/modalCategoryTransportation.imageset/Contents.json
- UMM/Assets.xcassets/Modal/modalCategoryUnknown.imageset/Contents.json
- UMM/Assets.xcassets/Record/recordTravelChoiceDownChevron.imageset/Contents.json
- UMM/View/Expense/AllExpenseView.swift
- UMM/View/Expense/ExpenseView.swift
- UMM/View/Expense/TodayExpenseDetailView.swift
- UMM/View/Expense/TodayExpenseView.swift
- #104
- ExpensView의 UI를 수정합니다.
- 고칠 점이 많아요..
> 🎨[#104] 와이파이 아이콘 수정합니다.

- UMM.xcodeproj/project.pbxproj
- UMM/View/Expense/AllExpenseView.swift
- UMM/View/Expense/ExpenseView.swift
- UMM/View/Expense/TodayExpenseView.swift
- UMM/View/Modal/TravelChoiceModalBinding.swift
- UMM/View/Travel/AddMemberView.swift
- UMM/View/Travel/AddTravelView.swift
- UMM/View/Travel/CompleteAddTravelView.swift
- UMM/View/Travel/NewView.swift
- UMM/ViewModel/AddMemberViewModel.swift
- UMM/ViewModel/TravelListViewModel.swift
- #104 
- ExpenseView 탭 뷰 수정
- 오류 해결 중
> ⚡️[#104] ExpenseView 탭 뷰 수정 및 오류 수정 중 입니다.

- UMM/View/Expense/CustomDatePicker.swift
- UMM/View/Travel/PreviousTravelView.swift
- UMM/View/Travel/UpcomingTravelView.swift
- #110 
- 기본 이미지 추가
- 데이터 픽커 추가
> ⚡️[#110] 수정 사항 반영

- UMM.xcodeproj/project.pbxproj
- UMM/View/Travel/UpcomingTravelView.swift
- #143
- CountryInfoModel을 싱글톤으로 바꾸면서 실제 사용에서 shared로 바꾸지 않은 두 줄의 코드를 수정했습니다.
-
- 발견 즉시 고쳐서 올립니다! 다음에는 머지하기 전에 실행 잘 되는지 확인하도록 노력할게요. (dev에 합치기 전에 브랜치를 구경하는 법을 옛날엔 알았는데 지금은 또 잘 모르겠네요.)
> 🐛[#143] 코드 두 줄 수정

- UMM.xcodeproj/project.pbxproj
- UMM/View/Modal/AddTravelRequestModal.swift
- UMM/View/Record/ManualRecordView.swift
- UMM/View/Record/RecordView.swift
- UMM/ViewModel/RecordViewModel.swift
- #146 
- RecordViewModel
- divideVoiceSentence()에서 소숫점 뒤의 셋째 자리 이하를 지우게 했습니다.
- 문장이 비어버리면 이후의 변화를 다른 문자열에 담아서 voiceSentence에는 결국 누적하게 했습니다. (이것으로, 말하고 조금 늦게 녹음 버튼에서 손을 떼었을 때 모든 정보가 없어져버리는 문제와 말을 멈추면 이전의 기록이 사라지는 문제가 약간 해결되었습니다. 하지만 불완전합니다.)
- RecordView
- 임시 기록을 하려고 할 때 여행 생성 권유하는 모달을 띄웠습니다. 아직 모달의 버튼 중 탭을 오가는 기능은 구현하지 않았습니다.
- 모달에서 임시 기록하기 누르면 보이는 여행 이름을 '-'에서 '임시 기록’으로 바꾸게 했습니다.
- 금액에 쉼표를 넣었습니다.
- 파이팅!!
- voiceSentence가 항상 누적되게 하려고 고민했습니다. 기본으로 가능해야 할 것 같은데, 이상하게도 그러한 세팅 방법을 찾지 못했습니다. 그래서 주어진 도구로 약간의 억지를 부려 구현했습니다. 방법은 아래와 같습니다:
- Speech Framework가 전달해주는 transcribedString의 갱신은 다음의 세 가지 종류입니다:
- 1, 직전의 문자열에 무언가를 더한 문자열로의 갱신
- 2, 직전의 문자열을 고친 문자열로의 갱신
- 3, 직전의 문자열을 없애버리고 새롭게 받아쓰기를 시작하는 문자열
- (정확히는 1과 2의 결합형도 있습니다.)
- 1과 2는 직전의 문자열을 '대체'해야 하고, 3은 직전의 문자열에 이어 '추가'해야 합니다.
- '추가'를 구현하기 위해 …
> 🎨 ⚡[#146] RecordViewModel과 RecordView를 개선합니다.

- UMM/Handler/findCurrentTravel.swift
- UMM/View/Modal/TravelChoiceInExpenseModal.swift
- UMM/View/Modal/TravelChoiceInRecordModal.swift
- UMM/View/Record/ManualRecordView.swift
- UMM/View/Record/RecordView.swift
- UMM/ViewModel/MainViewModel.swift
- UMM/ViewModel/ManualRecordViewModel.swift
- UMM/ViewModel/RecordViewModel.swift
- #202
- #204
- ManualRecordView 이니셜라이저를 없애니 많은 문제가 해결되었습니다.
-
- 모달의 이니셜라이저도 없앴습니다.
> 🐛[#202][#204] 디버그했습니다.

- UMM/View/Expense/AllExpenseDetailView.swift
> :bug:[#249] AllDetail 빨간 글씨 수정

- UMM/View/Record/InterimPastView.swift
- UMM/View/Travel/PreviousTravelView.swift
- UMM/ViewModel/ExpenseViewModel.swift
> 🎨[#249] Default 뷰 수정합니다.

- UMM/Dummy/TempSave.swift
- UMM/Handler/findCurrentTravel.swift
- UMM/View/Travel/AddMemberView.swift
- #249 
- TempSave()에 숨겨져있던 임시 기록을 찾아서 되살려냈다
> :bug:[#249] 임시 기록을 되살려냈다

- UMM/Extension/Date+Extension.swift
- UMM/ViewModel/ManualRecordInExpenseViewModel.swift
- #249
- ManualRecordInExpenseView에서 날짜 피커 에러
> :bug:[#249] ManualRecordInExpenseView에서 날짜 피커 에러

- UMM/View/Expense/AllExpenseDetailView.swift
- #290 
- AllExpenseDetailView에서 마지막 날에는 하단 divider 삭제
- AllDetailView 백 버튼에 이전 국가 추가
> 🎨 [#290] AllDetailView의 gui를 수정했습니다.

- UMM/View/MainView.swift
- #340
- 탭바 위에 gray100 줄을 그었습니다.
- 라딘이 도와주었습니다!
> 🎨 [#340] 탭바 위에 줄 긋기 구현

- UMM.xcodeproj/project.pbxproj
- UMM/Info.plist
- UMM/View/Expense/CSVArchive.swift
- #345 
- .csv 관련 info.plist를 수정했습니다.
- `com.example.csv`에서 `com.UMM.csv`로 변경했습니다.
- 배포 과정에서 문제가 없는지 확인해야 합니다.
> :broom:[#345] .csv 관련 info.plist를 수정합니다.
